import { metrics, residentRequests, workOrders } from '../../data/dashboard'
import { Icon } from '../../components/Icon'

export function Dashboard({ query }: { query: string }) {
  const requests = residentRequests.filter((item) => `${item.unit} ${item.name} ${item.detail}`.toLowerCase().includes(query.toLowerCase()))
  return <><section className="metric-grid">{metrics.map((item) => <article className="metric-card" key={item.label}><span className={`metric-icon ${item.tone}`}><Icon name={item.icon} /></span><label>{item.label}</label><strong>{item.value}</strong><small className={item.tone}><Icon name={item.trend} />{item.note}</small></article>)}</section><section className="insight-grid"><article className="panel finance"><PanelTitle eyebrow="TÀI CHÍNH" title="Tiến độ thu phí" /><div className="amount"><strong>2.860.000.000 đ</strong><span>trên 3.398.000.000 đ</span></div><div className="progress"><i /></div><div className="chart">{[38,52,45,70,60,86,76].map((height, index) => <i key={index} className={index === 6 ? 'today' : ''} style={{ height: `${height}%` }} />)}</div><div className="chart-labels"><span>T2</span><span>T3</span><span>T4</span><span>T5</span><span>T6</span><span>T7</span><span>CN</span></div></article><article className="panel occupancy"><PanelTitle eyebrow="CÔNG SUẤT" title="Trạng thái căn hộ" /><div className="donut"><div><strong>96,8%</strong><span>Đã lấp đầy</span></div></div><div className="legend"><span><i className="occupied" />Đang ở <b>1.208</b></span><span><i className="available" />Còn trống <b>28</b></span><span><i className="maintenance" />Bảo trì <b>12</b></span></div></article><article className="panel systems"><PanelTitle eyebrow="HỆ THỐNG" title="Trạm vận hành" /><span className="online"><i />TRỰC TUYẾN</span><Node icon="dns" title="Central Node 01" note="Hoạt động ổn định" rate="99,98%" /><Node icon="videocam" title="Camera an ninh" note="128 / 128 đang trực tuyến" rate="100%" /><button className="link-button">Xem bảng điều khiển hệ thống <Icon name="arrow_forward" /></button></article></section><section className="content-grid"><article className="panel"><PanelTitle eyebrow="CƯ DÂN" title="Hồ sơ cần tiếp nhận" action="Xem tất cả" />{requests.map((item) => <div className="resident-row" key={item.unit}><span className="resident-avatar">{item.name[0]}</span><div><strong>{item.name}</strong><small>{item.detail}</small></div><div className="unit"><strong>{item.unit}</strong><small>{item.time}</small></div><span className={`badge ${item.tone}`}>{item.status}</span><Icon name="chevron_right" /></div>)}{!requests.length && <p className="empty">Không tìm thấy hồ sơ phù hợp.</p>}</article><article className="panel"><PanelTitle eyebrow="KỸ THUẬT" title="Phiếu công việc gần đây" />{workOrders.map((item) => <div className="work-order" key={item.code}><span className="work-icon"><Icon name="construction" /></span><div><strong>{item.title}</strong><small>{item.code} · {item.location}</small></div><span className="badge blue">{item.status}</span></div>)}</article></section></>
}
function PanelTitle({ eyebrow, title, action }: { eyebrow: string; title: string; action?: string }) { return <div className="panel-title"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{action ? <button className="link-button">{action} <Icon name="arrow_forward" /></button> : <button className="more"><Icon name="more_horiz" /></button>}</div> }
function Node({ icon, title, note, rate }: { icon: string; title: string; note: string; rate: string }) { return <div className="node"><span><Icon name={icon} /></span><div><strong>{title}</strong><small>{note}</small></div><b>{rate}</b></div> }
